### ISSUE TITLE
util.parseURL does not work on Windows

### ISSUE THREAD

**Issue by christsim** [bcoin-org/bweb#2]
Hi.

I'm actually trying to run bcoin on a windows machine, however it fails trying parse urls on incoming requests from nodeClient and walletClient.

I've narrowed it down to the `parseURL` function:
https://github.com/bcoin-org/bweb/blob/67c03db5c2e4ecf5b9c9fac681c2f08d90aa5601/lib/util.js#L49
`Path.normalize` does not behave the same on Windows as it does on Unix based oses:

on Windows:
```
node
> var path = require('path');
undefined
> path.normalize('/')
'\\'
```

on Ubuntu:
```
node
> var path = require('path');
undefined
> path.normalize('/')
'/'
```

Thanks,
Chris

**Comment by ripper234** [comment]
+1 just ran into this as well.

Just for easier Googling, the `cli` utility emits "socket hang up" and the server just displays on console:

[error] (node) false == true

I found the cause for the assertion only when I opened the debug.log file.
